-- 000004_auth.down.sql
DROP INDEX IF EXISTS devices_org_idx;
DROP INDEX IF EXISTS devices_tenant_idx;
ALTER TABLE devices DROP COLUMN org_unit_id CASCADE;
ALTER TABLE devices DROP COLUMN tenant_id CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS user_org_scopes CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS org_units CASCADE;
DROP TABLE IF EXISTS tenants CASCADE;